order:
  label: order
  replicas: 1
  containerPort: 9070
  image: default
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Gi
  averageUtilization:
   cpu: 60
   memory: 60
  service:
    type: ClusterIP
    port: 9070

secret:
  label: order-secret
  SPRING_DATA_MONGODB_URI_ORDER: PROVIDED_VIA_GITHUB_ACTIONS

config:
  label: order-config-map
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-svc:80/eureka/
  EUREKA_INSTANCE_HOSTNAME: order-svc