category:
  label: category
  replicas: 1
  containerPort: 9000
  image: dharshib/purely-category-service:latest
  service:
    type: ClusterIP
    port: 9000

secret:
  label: category-secret
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8761/eureka/
  SPRING_DATA_MONGODB_URI_CATEGORY: YOUR_MONGODB_URI