category:
  label: category
  replicas: 1
  containerPort: 9000
  image: default
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
  averageUtilization:
   cpu: 60
   memory: 60
  service:
    type: ClusterIP
    port: 9000

secret:
  label: category-secret
  SPRING_DATA_MONGODB_URI_CATEGORY: PROVIDED_VIA_GITHUB_ACTIONS

config:
  label: category-config-map
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-svc:80/eureka/
  EUREKA_INSTANCE_HOSTNAME: category-svc