apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-depl" .Values.product.label }}  
  labels:
    app: {{ .Values.product.label }}
spec:
  replicas: {{ .Values.product.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.product.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.product.label }}
    spec:
      containers:
        - name: {{ printf "%s-container" .Values.product.label }}
          image: {{ .Values.product.image }}
          ports:
            - containerPort: {{ .Values.product.containerPort }}
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.config.label }}
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.label }}
                  key: SPRING_DATA_MONGODB_URI_PRODUCT
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.config.label }}
                  key: EUREKA_INSTANCE_HOSTNAME
          resources:
            requests:
              cpu: {{ .Values.order.requests.cpu }}
              memory: {{ .Values.order.requests.memory }}
            limits:
              cpu: {{ .Values.order.limits.cpu }}
              memory: {{ .Values.order.limits.memory }}