apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc" .Values.notification.label }} 
spec:
  selector:
    app: {{ .Values.notification.label }}
  ports:
    - port: {{ .Values.notification.service.port }}
      targetPort: {{ .Values.notification.containerPort }}
      protocol: TCP
  type: {{ .Values.notification.service.type }}