cart:
  label: cart
  replicas: 1
  containerPort: 9060
  image: default
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
  averageUtilization:
   cpu: 60
   memory: 60
  service:
    type: ClusterIP
    port: 9060

secret:
  label: cart-secret
  SPRING_DATA_MONGODB_URI_CART: PROVIDED_VIA_GITHUB_ACTIONS

config:
  label: cart-config-map
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-svc:80/eureka/
  EUREKA_INSTANCE_HOSTNAME: cart-svc