apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc" .Values.gateway.label }} 
spec:
  selector:
    app: {{ .Values.gateway.label }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.containerPort }}
      protocol: TCP
  type: {{ .Values.gateway.service.type }}