auth:
  label: auth
  replicas: 1
  containerPort: 9030
  image: default
  service:
    type: ClusterIP
    port: 9030

secret:
  label: auth-secret
  SPRING_DATA_MONGODB_URI_AUTH: PROVIDED_VIA_GITHUB_ACTIONS

config:
  label: auth-config-map
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-svc:80/eureka/
  EUREKA_INSTANCE_HOSTNAME: auth-svc