web:
  label: web-app
  replicas: 1
  containerPort: 80
  image: default
  requests:
    cpu: 1000m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
  averageUtilization:
   cpu: 60
   memory: 60
  service:
    type: ClusterIP
    port: 80
    