apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.label }}
type: Opaque
data:
  SPRING_DATA_MONGODB_URI_CATEGORY: {{ .Values.secret.SPRING_DATA_MONGODB_URI_CATEGORY | toString | b64enc }}
