spring:
    application:
        name: user-service
    data:
        mongodb:
            uri: 
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9050

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/