spring:
    application:
        name: product-service
    data:
        mongodb:
            uri: 
    jpa:
        hibernate:
            ddl-auto: update
    ai:
        mcp:
            server:
                enabled: true
                protocol: STREAMABLE
                name: product-mcp-server
                version: 1.0.0
                type: SYNC
                annotation-scanner:
                    enabled: true
                tool-change-notification: true
                streamable-http:
                    mcp-endpoint: /mcp
                    keep-alive-interval: 30s
                capabilities:
                    prompt: false
                    resource: false
                    completion: false

management:
    endpoints:
        web:
            exposure:
                include: mappings

logging:
    level:
        org:
            springframework:
                web: DEBUG
                ai:
                    mcp: TRACE
                io:
                    modelcontextprotocol: TRACE

server:
    port: 9010

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost