apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc" .Values.auth.label }} 
spec:
  selector:
    app: {{ .Values.auth.label }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.containerPort }}
      protocol: TCP
  type: {{ .Values.auth.service.type }}