name: CI/CD Pipeline Notification Service

on: 
   push:
      branches:
         - docker
      paths:
         - 'microservice-backend/notification-service/**'

jobs:
   containerize-notification-service:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code  
           uses: actions/checkout@v4

         - name: Set up Java
           uses: actions/setup-java@v3
           with:
               java-version: '17'
               distribution: 'temurin'

         - name: build and push the docker image to dockerhub
           run: |
               docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

               docker build -t ${{ secrets.DOCKER_USERNAME }}/purely-notification-service:latest ./microservice-backend/notification-service
               docker push ${{ secrets.DOCKER_USERNAME }}/purely-notification-service:latest
