name: CI/CD Pipeline Web Application

on: 
   push:
      branches:
         - docker
      paths:
         - 'frontend/**'

jobs:
   containerize-web-app:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code  
           uses: actions/checkout@v4

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
               node-version: 20

         - name: build and push the docker image to dockerhub
           run: |
               docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

               docker build -t ${{ secrets.DOCKER_USERNAME }}/purely-web-app:latest ./frontend
               docker push ${{ secrets.DOCKER_USERNAME }}/purely-web-app:latest
